language: python
python:
    - 3.4
    - 3.3
    - 2.7
sudo: false
before_install:
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
    
install:
    - pip install -f travis-wheels/wheelhouse -e . coveralls -r requirements.txt
    - pip install  -f travis-wheels/wheelhouse jupyter_client[test]
    - python -c 'import ipykernel.kernelspec; ipykernel.kernelspec.install(user=True)'
script:
    - nosetests --with-coverage jupyter_client
after_success:
    - coveralls
