language: python
python:
    - "nightly"
    - "3.8-dev"
    - "3.7"
    - "3.6"
    - "3.5"
install:
  - pip install --upgrade setuptools pip
  - pip install --upgrade --upgrade-strategy eager --pre -e .[test] pytest-cov pytest-warnings codecov
  - pip freeze
script:
  - py.test --cov jupyter_client jupyter_client
after_success:
  - codecov
matrix:
    allow_failures:
        - python: nightly
branches:
  except:
    - /^auto-backport-of-pr-[0-9]+$/
